[package]
name = "percentiletracker"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
rand = "0.9"
rand_chacha = "0.9"
criterion = "0.5"

[[bench]]
name = "percentile_tracker_benchmarks"
harness = false

# Disable automatic benchmarks
[lib]
bench = false
